import axios from "axios";
export default {
   handleBanner({commit}){
   	axios({
   		methods:"get",
   		// https://m.maizuo.com/v4/api/billboard/home?__t=1541905558870
   		 url:"http://localhost:3000/list1",

   	}).then((data)=>{
   		commit("handleBanner",data.data);
   	})

   },
   handleCloth({commit},params){
	if(params<5){
		console.log(params)
			axios({
							method:"get",
					url:"http://localhost:3000/yifu?_page="+params+"&_limit=2",
							// url:"http://localhost:8080/static/json/list.json?_page="+params+&_limit="4",
							}).then((data)=>{
							commit("handleCloth",data.data)
							})
			}
   },
   handleTehui({commit,state},params){
    console.log(params);
	  if(params[0]<3){
   	axios({
   		method:"get",
   		url:"http://www.bmyss.xyz:8080/bmys/discounts/moduleOneGoodsList?pageNum="+params[0]+"&goodsTypeId="+params[1],
   		}).then((data)=>{
   		commit("handleTehui",data.data.data.data);
   		})
		 }
  },
     handleTehui1({commit,state},params){
			if(params[0]<3){
      axios({
     	method:"get",
     	url:"http://www.bmyss.xyz:8080/bmys/discounts/moduleTwoGoodsList?pageNum="+params[0]+"&"+"goodsTypeId="+params[1],
     	}).then((data)=>{
     	commit("handleTehui1",data.data.data.data)
     })
		 }
    },
	handleTehui2({commit,state},params){
	if(params[0]<3){
	axios({
		method:"get",
		url:"http://www.bmyss.xyz:8080/bmys/discounts/moduleThreeGoodsList?pageNum="+params[0]+"&"+"goodsTypeId="+params[1],
		}).then((data)=>{
		commit("handleTehui2",data.data.data.data);
	})
	}
	},
	handleTehui3({commit,state},params){
	if(params[0]<3){
	axios({
		method:"get",
		url:"http://www.bmyss.xyz:8080/bmys/discounts/moduleFourGoodsList?pageNum="+params[0]+"&"+"goodsTypeId="+params[1],
		}).then((data)=>{
		commit("handleTehui3",data.data.data.data)
	})
	}
	},
   handleSmall({commit}){
   axios({
   	method:"get",
   	url:"http://www.bmyss.xyz:8080/bmys/goods/getAllGoodsType",
   	}).then((data)=>{
   	commit("handleSmall",data.data.data);
   	})
   },
   handleId({commit},index){
	   commit("handleId",index);
   },
   handleTwopicture({commit},params){
	if(params.pageNum<6){
	  axios({
	  	method:"get",
	  	url:"http://www.bmyss.xyz:8080/bmys/goods/findGoodsByTypeId?pageNum="+params.pageNum+"&_limit=4"+"&typeId_1="+params.id,
	  	}).then((data)=>{
	  	commit("handleTwopicture",data.data.data.data)
	  })
		}
   },
	 handleRoute({commit,state},params){
		 state.sptu=[];
		 axios({
		 	method:"get",
		 	url:"http://www.bmyss.xyz:8080/bmys/goods/findGoodsByTypeId?pageNum="+params.pageNum+"&_limit=4"+"&typeId_1="+params.id,
		 	}).then((data)=>{

		 	commit("handleTwopicture",data.data.data)
		 })
	 },
	 handleMenu({commit},params){
		 axios({
		 	methods:"get",
		 	url:"http://localhost:3000/list"
		 }).then((data)=>{
			commit("handleMenu",data.data)

		 })
	 },
	 handleFind({commit},params){
		 if(params.pageNum<2){
		 axios({
		 	method:"get",
		 	url:"http://www.bmyss.xyz:8080/bmys/goods/searchGoods?input="+params.val+"&pageNum="+params.pageNum,
		 	}).then((data)=>{
		   commit("handleFind",data.data.data.data);
		 })
		}
	 }
}
